### ISSUE TITLE
Analyze 2018-12-08 UCSF MEA Data

### ISSUE THREAD

**Issue by rcurrie** [braingeneers/experiment#1]
Jack, Sergio and @masonhargrave recorded data from 4 organoids on 11-08-2018 at UCSF. The data has been uploaded to the GI servers under braingeneers/mea/ucsf/11-08-2018:

```
├── organoid\ 1
│   ├── recording_1_181208_122247.rhd
│   ├── recording_1_181208_122347.rhd
│   ├── recording_2_100Hz\ high\ pass_181208_122907.rhd
│   ├── recording_2_100Hz\ high\ pass_181208_123007.rhd
│   ├── recording_3_one\ ref_181208_124702.rhd
│   ├── recording_3_one\ ref_181208_124802.rhd
│   ├── recording_4_one\ ref_High\ pass\ 250Hz_181208_124836.rhd
│   ├── recording_5_second_ref_100Hz_filter_181208_125448.rhd
│   ├── recording_6_second_ref_181208_125448_181208_125545.rhd
│   ├── recording\ background\ 100Hz\ filter_181208_130030.rhd
│   └── recording_background_181208_125938.rhd
├── organoid\ 2
│   ├── recording_1_181208_130814.rhd
│   ├── recording_2_100Hz_181208_130904.rhd
│   ├── recording_3\ wt_100hz\ filter_181208_135611.rhd
│   ├── recording_3\ wt_100hz\ filter_181208_135711.rhd
│   ├── recording_3\ wt_181208_135431.rhd
│   ├── recording_3\ wt_181208_135531.rhd
│   ├── recording_3\ wt_low\ freq\ noise_181208_140344.rhd
│   ├── recording_3\ wt_low\ freq\ noise_181208_140444.rhd
│   ├── recording_3\ wt_low\ freq\ noise_2_181208_140551.rhd
│   ├── recording_3\ wt_low\ freq\ noise_2_181208_140651.rhd
│   ├── recording_3\ wt_low\ freq\ noise_2_181208_140751.rhd
│   ├── recording_3\ wt_low\ freq\ noise_2_181208_140851.rhd
│   └── recording_background\ before\ organoid\ 2_181208_130214.rhd
├── organoid\ 3
│   ├── recording_4_wt_40mM\ KCl_181208_142127.rhd
│   ├── recording_4_wt_40mM\ KCl_181208_142227.rhd
│   ├── recording_4_wt_40mM\ KCl_181208_142327.rhd
│   └── recording_4_wt_40mM\ KCl_181208_142427.rhd
└── organoid\ 4
    ├── recording_4_wt\ 40mM\ KCl_181208_143357.rhd
    ├── recording_4_wt\ 40mM\ KCl_181208_143157.rhd
    ├── recording_4_wt\ 40mM\ KCl_181208_143257.rhd
    ├── recording_4_wt\ 40mM\ KCl_181208_143357.rhd
```
All: 16 outputs, 4 of which were not touching

1 & 2: Baseline recordings made w/o organoid but with media (brain serum). Then organoid added and recordings made with various filter settings on the MEA board.

3 & 4: Recordings start with organoid in place. Then KCl was added via pipette. Recording continued through addition and after.

@kvoitiuk @naveedziari @ashsrobbins are going to take a crack at analyzing these data by reading using python (see [notes](https://github.com/braingeneers/braingeneers/wiki/File-Formats) on reading files including using python) and analyzing in notebooks. Starting this issue to track progress and for everyone to chime in with any other details on the experiment.

**Comment by naveedziari** [comment]
organoid 1 has 17 readings. given that we have 16 electrodes, can anyone please explain this?

**Comment by rcurrie** [comment]
@SergioCor any color on @naveedziari question about 16 vs. 17 readings?

**Comment by SergioCor** [comment]
Sorry for my late reply. I’m currently on vacation and have limited access to a good WiFi signal. I cannot give a definitive reason for the extra channel. Before taking any recordings we only had 16 channels active.

**Comment by rcurrie** [comment]
@SergioCor @mirceasvt @kvoitiuk The Intan source code has the following line:

data['amplifier_data'] = np.multiply(0.195, (data['amplifier_data'].astype(np.int32) - 32768))      # units = microvolts

Is the Intan really measuring MICRO volts vs. MILLIVOLTS?

If micro then isn't that way way below what a neuron should be generating?

**Comment by rcurrie** [comment]
@SergioCor A few of the recordings have 17 channels (organoid 1/recording_2_100Hz high pass_181208_122907.rhd) while all the rest have 16. Any color on this?

**Comment by rcurrie** [comment]
Note I've restructured the ingested data to match treehouse towards a bit better data lifecycle - will discuss on Monday's meeting but briefly from a thread on Slack:

Tinkering with how we should organize all these data for analysis and lifecycle. For genomic projects we often break things down into primary/original (FASTQ), primary/derived (aligned BAM), secondary (VCF, Expression) and tertiary (analysis toward clinical recommendations). We archive primary/original up to Amazon Glacier and after 90 days delete all primary original and derived from various systems otherwise storage grows in an un-controlled manner. Its early in this area but it seems to me spike sorting is sort of like secondary output ie small relative to the original and what much of the downstream analysis will rely on. If so then primary/original would be the raw recordings (Intan .rhd for example or images) that we would want to archive. primary/derived would be transformed raw files but still relatively large but that we can expire as we can re-create from original, and secondary would be spike sorted, or features from processed images and significantly smaller then the primary and what most people on the team internal and external will care about.

**Comment by rcurrie** [comment]
@mirceasvt @ashsrobbins @naveedziari @haussler I've been glossing over the units on the graphs. The output from the Intan is apparently in MICRO volts. Take a look at this organoid 4 experiment. The steady state before adding KCl is down in the < 20 micro volts. After KCl is added the signal is up in the ~4 MILLIVOLT range. 

[Open in Colab](https://colab.research.google.com/github/rcurrie/notebooks/blob/master/braingeneers/2018-12-11-mea-ucsf.ipynb)

![image](https://user-images.githubusercontent.com/492570/50709845-07f3eb00-101e-11e9-8ea6-0f60d755c045.png)
![image](https://user-images.githubusercontent.com/492570/50709853-0fb38f80-101e-11e9-9706-55c818b9fb56.png)
![image](https://user-images.githubusercontent.com/492570/50709861-13471680-101e-11e9-9744-3135d22160fd.png)

**Comment by haussler** [comment]
Very good point! An action potential during neuron firing takes the
membrane voltage from about -70 millivolts to +40 millivolts, a change of
about 100 millivolts = 0.1 volt. This is many orders of magnitude beyond
what we are seeing in the live organoid before the KCL is added. After the
KCL is added, you get 4 millivolt waves at a frequency of about 3 per
second. Could be periodic motion of charged ions?

**Comment by rcurrie** [comment]
The x-axis on the original figures was wrong due to a coding error. I've fixed it in the original comment above. The periodic one is reproduced here for convenience. Unfortunately the overall patern is ~15msec or ~66 Hz. Maybe with the addition of the KCl the 60Hz AC signal is amplified. But there is still some higher frequency signal, and the overall has some distinct peaks that don't look like 60Hz AC to me.

![image](https://user-images.githubusercontent.com/492570/50729086-992f9400-10e8-11e9-8397-bd77589ec53b.png)

**Comment by ashsrobbins** [comment]
I'm starting to find some interesting things. Here is the difference between the background tests and an experiment with an organoid-
Background noise:
![background_noise](https://user-images.githubusercontent.com/13567475/50732225-462b0080-112b-11e9-8031-93ee86bdf82f.PNG)

Organoid:
![organoid_1_rec_3](https://user-images.githubusercontent.com/13567475/50732228-580ca380-112b-11e9-95f0-03bcabca3746.PNG)

Where one axis is time, the other is each of the electrodes, and the Z axis represents Voltage. We can see that all but two electrodes give similar signals here, however during just the background shows no differences. I'm currently working on a frequency analysis version to remove noises, and another version to show similarity of activity with between electrodes(along with running it through the KCL samples). However I've got working visualizations, now I'll try for some deeper analysis.


Also, I understand there is no true reason to create a surface in the manner they are in currently, between electrodes with corresponding indexes. However the relative heights help give vague insights for further analysis. If anyone has ideas on a better way to visualize them, I'm all ears. Also, if we can get spacial location of these electrodes, we can create true arrays of surfaces that match reality, or moving visualizations of signal propagation.

**Comment by mirceasvt** [comment]
Really cool Ash — which are the electrodes that have similar signal before and after the organoid was added?

The spectral analysis would be interesting.

Thank you and best wishes,
Mircea


--------------------------------- 
Mircea Teodorescu 

Baskin School of Engineering, UC Santa Cruz, 
1156 High Street, MS: SOE-3
Santa Cruz, CA 95064, USA
http:/danser.soe.ucsc.edu/
---------------------------------

**Comment by rcurrie** [comment]
For comparison Shinya provided some raw .RDF files from one of his mouse probe experiments (uploaded to /public/groups/braingeneers/samples/silicon-probe, not wrangled to .npy yet):

Note: I have not verified the Y axis units. He also provided spike output as a .mat, will ingest and add as annotation soon.

![image](https://user-images.githubusercontent.com/492570/50869139-a312fa80-1367-11e9-90c9-1e0d06b5ada6.png)
![image](https://user-images.githubusercontent.com/492570/50869145-a6a68180-1367-11e9-894e-27fd00da4278.png)
![image](https://user-images.githubusercontent.com/492570/50869148-ab6b3580-1367-11e9-8b81-61062da8eb0c.png)

**Comment by haussler** [comment]
great to have these mouse data!

**Comment by rcurrie** [comment]
Additional notes from Shinya: "The mouse was running between 20 and 25 s, and that was the reason for 8 Hz oscillation (steps of the mouse)."

**Comment by rcurrie** [comment]
I've wrangled the mouse data into .npy using a preliminary data repository layout detailed [here](https://github.com/braingeneers/braingeneers/wiki/data-repository-layout). We'll discuss this a bit at Monday's data team meeting.

**Comment by ashsrobbins** [comment]
So I thought we previously milked the data for what it's worth. We have signals that have the potential to be spikes, yet we can't distinguish them until we have a higher sampling rate(but we already knew this). A higher sampling rate will also let us categorize different spikes.

At some point there is definitely the need/want to apply machine learning to this, so I decided to implement a TCN on this data to try and just determine organoid/no organoid. I haven't implemented batch training yet so it takes a while to train currently.
The summary(I'll put the :

- I merged all of the corresponding recordings together

- Split the data into 1 second clumps(2000 time-steps of .5ms)

- Trained 1 layer temporal convolutional network(TCN)

- After a few epochs stabilize around 65-75% accuracy, working as well on the test set

If we could get SHAP to work on recurrent data that would be interesting, also I'd just like to run it longer too.

[**colab notebook**](https://colab.research.google.com/drive/13QFifM8CBAyl9eT9G72qrBM4os-VGhE0)

**Comment by rcurrie** [comment]
This is fantastic - extra points for the colab link :-)

Some thoughts:

Sample rate: Higher because multiple neurons are likely being picked up by a single MEA pad? If so makes sense. If not then its not clear to me why 20kHz isn't plenty given the bandwidth of a single neuron.

SHAP: There are a few issues in the SHAP repo on applying it to RNN's. Reference to [this paper](https://arxiv.org/abs/1802.07814) out of berkeley that mentions LSTMs. Need to debate exactly what we're trying to explain. For example if we spike sort the output and then train on that then maybe we want to explain which spikes go with which inputs which might just work with a reasonable input window viewed as a single example.

Split input sets: Nice generator! Moving from .tfrecord to .npy means we will not be able to partially load an input sample. There is the ability to memory map .npy but that won't work over https. We could switch to h5 but that has other issues. We may want to keep the individual .rhd blocks as individual .npy so that we can batch load like they do with image data sets (with each image separate). Let's ruminate and discuss next week as the recording time on these experiments is likely to exceed memory soon...

No need to credit me on code snippets, and I would say the same for this team as we'll be throwing this stuff all over the place. Lineage and credit = git + papers

**Comment by naveedziari** [comment]
Nice Job Ash!!! I was personally hesitant on making a classifier until we do an experiment with all conditions being organdies (e.g. control organoid vs glutamate), but this is a great start!
