### ISSUE TITLE
Convert .rdf and meta data into .npy and make available on S3 for colab access

### ISSUE THREAD

**Issue by rcurrie** [braingeneers/experiment#2]
The [python code from intan](http://intantech.com/RHD2000_evaluation_system.html) nicely converts a .rhd file to a structured dictionary easily manage via np.save/np.load. I’ve created an [ingest notebook](https://github.com/braingeneers/experiment/blob/master/ingest/ingest.ipynb) that reads the raw MEA intan .rdf files, converts them to numpy (with some wrangling for space) and uploads them to S3 so they can be read and easily analyzed publicly. See the [view notebook](https://github.com/braingeneers/experiment/blob/master/ingest/view.ipynb) for an example of how to load (click on the colab button to open in colab).

I’ve only converted and uploaded the Organoid 3 experiment but if this seems like a reasonable way to go I’ll convert all the rest so everyone can easily analyze (BTW scipy.signal is in colab…yay!).

Design issues for debate:
- amplfier_data is the largest component and probably should be split out into a separate .npy file with all the rest in a metadata.json file so we can index and search it without loading the actual data.
- I'm uploaded with mirrored paths to S3 but with space as '-'...later we'll want to switch to something more general where each file is stored via GUID (or hash) with the json containing all the magic
- @naveedziari the ingest IMHO is where we should drop spacial information. If you point me to something that looks like it I'll take a crack at putting faux fields into this export
- I'm converting to 16 bit but its still larger then the source file by more then I'd like...

**Comment by rcurrie** [comment]
The data files have 3 aux_input_data signals that appear to be all identical:

array([[2.451009, 2.451009, 2.451009, ..., 2.451009, 2.451009, 2.451009],
       [2.451009, 2.451009, 2.451009, ..., 2.451009, 2.451009, 2.451009],
       [2.451009, 2.451009, 2.451009, ..., 2.451009, 2.451009, 2.451009]])

Sized for the top level keys for a given file in MB

notes 0
supply_voltage_channels 0
t_supply_voltage 0
amplifier_channels 0
aux_input_data 4
amplifier_data 25
spike_triggers 0
t_amplifier 6
t_aux_input 1
supply_voltage_data 0
frequency_parameters 0
t_temp_sensor 0
aux_input_channels 0

I'm thinking we can simplify down to just the amplifier data as a separate file.

@SergioCor @masonhargrave  Do you think we need the aux or temp channels?

**Comment by rcurrie** [comment]
I've simplified the the output a bit by dropping all of the redundant time steps and everything except the actual amplifier data. I've also split the output into a pure .npy file with the amplifier data and a separate .json file with all the meta data. This will allow for future searching/indexing of the meta data without bringing all the actual data into memory.  This also brings the overall size of both down to roughly what the original is.

**Comment by naveedziari** [comment]
Hi Rob,

Sorry I’ve been MIA with all the resources you’ve been emailing us. I just wanted to finish what I started on Matlab, and now I can get to work with python. BTW, if you have admin privileges, can you please go to the Data folder in the shared drive and delete the Microsoft Office files I uploaded? I ended up converting to google format and modifying, so the Excel and PPT files are no longer relevant. 

Thanks,
Naveed

**Comment by rcurrie** [comment]
I don’t have admin access so can't delete the files (and happy I can’t actually :-)

Can you delete them? If not suggest forwarding to Kate. Should also put into a new folder named like the rest of the other folders.

Rob

**Comment by kvoitiuk** [comment]
Hi all,

I made a new folder called Braingeneers/Data/ *12/15/18 UCSF MEA Recording
1*.
All files are transferred there, PPT is deleted.

Let me know if any other changes are needed.

Best,
Kate
